/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as SwshApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const CreateAlbumRequest: core.serialization.Schema<serializers.CreateAlbumRequest.Raw, SwshApi.CreateAlbumRequest>;
export declare namespace CreateAlbumRequest {
    interface Raw {
        name: serializers.AlbumName.Raw;
    }
}
