/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as SwshApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const DeleteAlbumRequest: core.serialization.Schema<serializers.DeleteAlbumRequest.Raw, SwshApi.DeleteAlbumRequest>;
export declare namespace DeleteAlbumRequest {
    interface Raw {
        albumId: string;
    }
}
