/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const DeleteAlbumRequest = core.serialization.object({
    albumId: core.serialization.string(),
});
