/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as SwshApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const EditAlbumRequest: core.serialization.Schema<serializers.EditAlbumRequest.Raw, SwshApi.EditAlbumRequest>;
export declare namespace EditAlbumRequest {
    interface Raw {
        albumId: string;
        name?: serializers.AlbumName.Raw | null;
    }
}
