/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as SwshApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const RequestBodyCreateAlbum: core.serialization.Schema<serializers.RequestBodyCreateAlbum.Raw, SwshApi.RequestBodyCreateAlbum>;
export declare namespace RequestBodyCreateAlbum {
    interface Raw {
        name: string;
    }
}
