/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SwshApi from "../../../..";
/**
 * @example
 *     {
 *         name: "My Album"
 *     }
 */
export interface CreateAlbumRequest {
    name: SwshApi.AlbumName;
}
