/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         albumId: "22222222-2222-2222-2222-222222222222"
 *     }
 */
export interface DeleteAlbumRequest {
    /** The ID of the album to delete */
    albumId: string;
}
