/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         albumId: "11111111-1111-1111-1111-111111111111"
 *     }
 */
export interface GetAlbumRequest {
    /**
     * ID of the album to retrieve
     */
    albumId: string;
}
