/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "My Album"
 *     }
 */
export interface RequestBodyCreateAlbum {
    name: string;
}
