/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import * as SwshApi from "./api";
import { Album } from "./api/resources/album/client/Client";
export declare namespace SwshApiClient {
    interface Options {
        environment?: core.Supplier<environments.SwshApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class SwshApiClient {
    protected readonly _options: SwshApiClient.Options;
    constructor(_options: SwshApiClient.Options);
    ping(requestOptions?: SwshApiClient.RequestOptions): Promise<SwshApi.ResponsePing>;
    protected _album: Album | undefined;
    get album(): Album;
}
