/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const SwshApiEnvironment: {
    readonly Default: "https://public-api.joinswsh.com";
};
export declare type SwshApiEnvironment = typeof SwshApiEnvironment.Default;
