/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const AlbumName: core.serialization.Schema<serializers.AlbumName.Raw, SwshApi.AlbumName>;
export declare namespace AlbumName {
    type Raw = string;
}
