/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const Album: core.serialization.ObjectSchema<serializers.Album.Raw, SwshApi.Album>;
export declare namespace Album {
    interface Raw {
        albumId: serializers.AlbumId.Raw;
        name?: serializers.AlbumName.Raw | null;
        ownerId?: string | null;
        shareUrl?: string | null;
        numPhotos?: number | null;
        numParticipants?: number | null;
    }
}
