/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const BadRequestErrorBody: core.serialization.ObjectSchema<serializers.BadRequestErrorBody.Raw, SwshApi.BadRequestErrorBody>;
export declare namespace BadRequestErrorBody {
    interface Raw {
        message: string;
    }
}
