/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const Cursor: core.serialization.Schema<serializers.Cursor.Raw, SwshApi.Cursor>;
export declare namespace Cursor {
    type Raw = string;
}
