/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const PreviewPhoto: core.serialization.ObjectSchema<serializers.PreviewPhoto.Raw, SwshApi.PreviewPhoto>;
export declare namespace PreviewPhoto {
    interface Raw {
        photoId: string;
        width?: number | null;
        height?: number | null;
        originalUrl: string;
        stableUrl: string;
    }
}
