/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const PreviewPhoto = core.serialization.object({
    photoId: core.serialization.string(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
    originalUrl: core.serialization.string(),
    stableUrl: core.serialization.string(),
});
