/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponseSingleAlbum: core.serialization.ObjectSchema<serializers.ResponseSingleAlbum.Raw, SwshApi.ResponseSingleAlbum>;
export declare namespace ResponseSingleAlbum {
    interface Raw {
        data: serializers.Album.Raw;
        warnings?: serializers.Warnings.Raw | null;
    }
}
