/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponsePreviewPhotos: core.serialization.ObjectSchema<serializers.ResponsePreviewPhotos.Raw, SwshApi.ResponsePreviewPhotos>;
export declare namespace ResponsePreviewPhotos {
    interface Raw {
        data: serializers.PreviewPhoto.Raw[];
        warnings?: serializers.Warnings.Raw | null;
    }
}
