/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponseAlbumsCursor: core.serialization.ObjectSchema<serializers.ResponseAlbumsCursor.Raw, SwshApi.ResponseAlbumsCursor>;
export declare namespace ResponseAlbumsCursor {
    interface Raw {
        data: serializers.Album.Raw[];
        cursor?: serializers.Cursor.Raw | null;
        warnings?: serializers.Warnings.Raw | null;
    }
}
