/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponsePing: core.serialization.ObjectSchema<serializers.ResponsePing.Raw, SwshApi.ResponsePing>;
export declare namespace ResponsePing {
    interface Raw {
        data: serializers.ResponsePingData.Raw;
        warnings?: serializers.Warnings.Raw | null;
    }
}
