/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponseSuccessData: core.serialization.ObjectSchema<serializers.ResponseSuccessData.Raw, SwshApi.ResponseSuccessData>;
export declare namespace ResponseSuccessData {
    interface Raw {
        message: string;
    }
}
