/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const ResponseSuccess: core.serialization.ObjectSchema<serializers.ResponseSuccess.Raw, SwshApi.ResponseSuccess>;
export declare namespace ResponseSuccess {
    interface Raw {
        data: serializers.ResponseSuccessData.Raw;
        warnings?: serializers.Warnings.Raw | null;
    }
}
