/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as SwshApi from "../../api";
import * as core from "../../core";
export declare const Warnings: core.serialization.Schema<serializers.Warnings.Raw, SwshApi.Warnings>;
export declare namespace Warnings {
    type Raw = string[];
}
