/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as SwshApi from "..";
export declare class BadRequestError extends errors.SwshApiError {
    constructor(body: SwshApi.BadRequestErrorBody);
}
