/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as SwshApi from "../../..";
export declare namespace Album {
    interface Options {
        environment?: core.Supplier<environments.SwshApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Album {
    protected readonly _options: Album.Options;
    constructor(_options: Album.Options);
    /**
     * @throws {@link SwshApi.BadRequestError}
     *
     * @example
     *     await swshApi.album.createAlbum({
     *         name: "My Album"
     *     })
     */
    createAlbum(request: SwshApi.RequestBodyCreateAlbum, requestOptions?: Album.RequestOptions): Promise<SwshApi.ResponseSingleAlbum>;
    /**
     * @throws {@link SwshApi.BadRequestError}
     * @throws {@link SwshApi.NotFoundError}
     *
     * @example
     *     await swshApi.album.getAlbum({
     *         albumId: "11111111-1111-1111-1111-111111111111"
     *     })
     */
    getAlbum(request: SwshApi.GetAlbumRequest, requestOptions?: Album.RequestOptions): Promise<SwshApi.ResponseSingleAlbum>;
    /**
     * @throws {@link SwshApi.BadRequestError}
     *
     * @example
     *     await swshApi.album.getAlbums({
     *         limit: 10
     *     })
     */
    getAlbums(request?: SwshApi.GetAlbumsRequest, requestOptions?: Album.RequestOptions): Promise<SwshApi.ResponseAlbumsCursor>;
}
