/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Album {
    albumId: string;
    name?: string;
    ownerId?: string;
    /** A URL that can be shared with others to view the album */
    shareUrl?: string;
}
