/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A cursor to be used in subsequent requests to retrieve the next page of results. If this is `{}`, there are no more results to retrieve.
 */
export declare type Cursor = string;
