/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PreviewPhoto {
    photoId: string;
    width?: number;
    height?: number;
    /** A signed URL to access the originally uploaded image */
    originalUrl: string;
    /** A signed URL to access the stable version of the image (JPEG, <15 MB) */
    stableUrl: string;
}
