/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SwshApi from "..";
export interface ResponsePing {
    data: SwshApi.ResponsePingData;
    warnings?: SwshApi.Warnings;
}
