/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SwshApi from "..";
export interface ResponsePreviewPhotos {
    data: SwshApi.PreviewPhoto[];
    warnings?: SwshApi.Warnings;
}
