/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SwshApi from "..";
export interface ResponseAlbumsCursor {
    data: SwshApi.Album[];
    cursor?: SwshApi.Cursor;
    warnings?: SwshApi.Warnings;
}
