/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SwshApi from "..";
export interface ResponseSingleAlbum {
    data: SwshApi.Album;
    warnings?: SwshApi.Warnings;
}
